### ISSUE TITLE
需要依赖的 require 包具体有哪些，在哪里下？

### ISSUE THREAD

**Issue by jandy0414** [mazzzystar/disco-diffusion-wrapper#1]
![image](https://user-images.githubusercontent.com/35617197/166855353-db255fac-fe14-4f79-a7e7-24a51b29111c.png)

**Comment by mazzzystar** [comment]
前面两个都是项目里的，比如`utils` 是:
```
https://github.com/mazzzystar/disco-diffusion-wrapper/blob/master/wrapper/utils.py
```

deepl这个是外部的，可以试试`pip install deepl`，我之后再补充一下环境配置信息~

**Comment by anonymity12** [comment]
pandas
timm
IPython
lpips
ftfy
regex
matplotlib
ipywidgets
einops
omegaconf
torch
opencv-python

**Comment by mazzzystar** [comment]
@jandy0414 
我把自己目前的环境用`pip freeze`导出了，可以pull下最新的代码。
```
 pip install -r requirements.txt
```
我猜模型用不到里面全部的pip包，希望可以帮到你。

**Comment by jandy0414** [comment]
> @jandy0414 我把自己目前的环境用`pip freeze`导出了，可以pull下最新的代码。
> 
> ```
>  pip install -r requirements.txt
> ```
> 
> 我猜模型用不到里面全部的pip包，希望可以帮到你。

===》 非常感谢，确实提供了有效帮助。但是遇到新问题
执行 python mutils.py 时 
这个pretrained 下的文件下载不了
单独去下载也下载不下来：
![image](https://user-images.githubusercontent.com/35617197/167242697-52edc967-e5d9-4050-800f-5a7c07d8a7da.png)


能否提供 类似放models 地方供下载

**Comment by jandy0414** [comment]
![image](https://user-images.githubusercontent.com/35617197/167243179-487b59d9-6420-4175-928c-4ca8eb9b1abd.png)

**Comment by mazzzystar** [comment]
https://cloudflare-ipfs.com/ipfs/Qmd2mMnDLWePKmgfS8m6ntAg4nhV5VkUyAydYBp8cWWeB7/AdaBins_nyu.pt
在Chrome里点击这个链接应该可以自动下载~

我的方式是：在Macbook本地用浏览器下载，然后使用Jupyter Notebook上传到服务器。

**Comment by jandy0414** [comment]
> 

> https://cloudflare-ipfs.com/ipfs/Qmd2mMnDLWePKmgfS8m6ntAg4nhV5VkUyAydYBp8cWWeB7/AdaBins_nyu.pt 在Chrome里点击这个链接应该可以自动下载~
> 
> 我的方式是：在Macbook本地用浏览器下载，然后使用Jupyter Notebook上传到服务器。

====
这个地址cloudflare-ipfs.com访问不了，我通过华为云服务器，阿里云服务器，也访问不了
您这个文件，能否换地方存放？？

**Comment by mazzzystar** [comment]
链接: https://pan.baidu.com/s/1lqXJAZ4mII38urI12r0drA?pwd=amty 提取码: amty 
我把这个模型上传到百度网盘了，再试试呢，不确定服务器能否使用网盘这种形式下载，但我没有自己的存储大文件的图床~

**Comment by jandy0414** [comment]
> 链接: https://pan.baidu.com/s/1lqXJAZ4mII38urI12r0drA?pwd=amty 提取码: amty 我把这个模型上传到百度网盘了，再试试呢，不确定服务器能否使用网盘这种形式下载，但我没有自己的存储大文件的图床~

可以下载，非常感谢！！
