### ISSUE TITLE
这个模块安装 不了 command-not-found

### ISSUE THREAD

**Issue by Aquietorange** [mazzzystar/disco-diffusion-wrapper#14]
这个模块安装 不了
ERROR: Could not find a version that satisfies the requirement command-not-found (from versions: none)
ERROR: No matching distribution found for command-not-found

**Comment by mazzzystar** [comment]
这个报错信息，看不到是哪个模块。如果有python包无法安装，可以先注释掉那一行，安装剩下的试试。

**Comment by ykk648** [comment]
https://github.com/mazzzystar/disco-diffusion-wrapper/blob/a4744c9e4bc02823d6491056bbcbb338ceb4fe85/requirements.txt#L27  应该可以直接删除

**Comment by mazzzystar** [comment]
@ykk648 谢谢指出，我更新一下依赖。

**Comment by Aquietorange** [comment]
事实上，一大堆模块 安装 不了，手动在 https://pypi.org/search/?q= 也搜不到的那种

**Comment by ykk648** [comment]
哈哈 以及 [](url)](https://github.com/mazzzystar/disco-diffusion-wrapper/blob/af5b9cf898d8dbfb62299c4890726801e0d897d6/requirements.txt#L39)

**Comment by ykk648** [comment]
以及 https://github.com/mazzzystar/disco-diffusion-wrapper/blob/af5b9cf898d8dbfb62299c4890726801e0d897d6/requirements.txt#L32  编译不过

**Comment by mazzzystar** [comment]
@ykk648 @Aquietorange 
谢谢提醒，我之前是用pip freeze把服务器环境保存下来的，刚用自己本地机器尝试重新安装，删掉了一些依赖。
总结规律就是：
1.如果该依赖的版本报错，修改`requirements.txt`，先不指定该package的版本再试试。
2.如果仍然不行，删掉该行。

**Comment by mazzzystar** [comment]
已经本地测试了`requirements.txt`里的所有安装，可以pull最新代码。
