### ISSUE TITLE
About translate！

### ISSUE THREAD

**Issue by kawayixixing** [mazzzystar/disco-diffusion-wrapper#17]
The deepl translate api for me to hard to apply, so i decide  to use English get the paint, but i follow the usage to `USE_TRANSLATE=False`, i get the translate problem，like this（run_batch.py and run.py are same）：
![P20715-120217](https://user-images.githubusercontent.com/45343530/179150199-00c6e871-7a11-4101-992a-d9ae3bded56d.jpg)

**Comment by mazzzystar** [comment]
You may try delete `del  translator` and re-run. Thanks for point out, I will fix this later
