### ISSUE TITLE
Pt resources could not be downloaded

### ISSUE THREAD

**Issue by destinyyg** [mazzzystar/disco-diffusion-wrapper#18]
![image](https://user-images.githubusercontent.com/76560946/179328635-16010858-ce29-4c31-9b57-53de68d1d004.png)

**Comment by mazzzystar** [comment]
sorry for the late response.
You could download models manualy, maybe you need a proxy.

**Comment by destinyyg** [comment]
![image](https://user-images.githubusercontent.com/76560946/182840046-8de3a87a-aab2-4f27-8fc6-3bfceca055f2.png)
However, there are no relevant resources for manual access
https://v-diffusion.s3.us-west-2.amazonaws.com/512x512_diffusion_uncond_finetune_008100.pt

**Comment by mazzzystar** [comment]
Thanks for the information, it's deleted by their owner.
You may download it from: 
https://huggingface.co/lowlevelware/512x512_diffusion_unconditional_ImageNet/blob/main/512x512_diffusion_uncond_finetune_008100.pt
