### ISSUE TITLE
Package versions have conflicting dependencies

### ISSUE THREAD

**Issue by aidots** [mazzzystar/disco-diffusion-wrapper#19]
ERROR: Cannot install -r requirements.txt (line 105), -r requirements.txt (line 17), -r requirements.txt (line 181), -r requirements.txt (line 44), -r requirements.txt (line 76) and -r requirements.txt (line 89) because these package versions have conflicting dependencies.

The conflict is caused by:
    jupyter-client 7.3.0 depends on python-dateutil>=2.8.2
    matplotlib 3.5.1 depends on python-dateutil>=2.7
    pandas 1.4.2 depends on python-dateutil>=2.8.1
    wandb 0.12.15 depends on python-dateutil>=2.6.1
    botocore 1.25.1 depends on python-dateutil<3.0.0 and >=2.1
    falco 0.4.0 depends on python-dateutil==2.8.1
    jupyter-client 7.3.0 depends on python-dateutil>=2.8.2
    matplotlib 3.5.1 depends on python-dateutil>=2.7
    pandas 1.4.2 depends on python-dateutil>=2.8.1
    wandb 0.12.15 depends on python-dateutil>=2.6.1
    botocore 1.25.1 depends on python-dateutil<3.0.0 and >=2.1
    falco 0.3.0 depends on python-dateutil==2.8.1

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by mazzzystar** [comment]
You may try delete all requirements lines that contains `falco` to see if it works.
