### ISSUE TITLE
建议的配置

### ISSUE THREAD

**Issue by 0xtaosu** [mazzzystar/disco-diffusion-wrapper#2]
你好，我想请教一下，建议的配置是什么呢？Macbook Pro可以跑吗

**Comment by mazzzystar** [comment]
抱歉应该是不可以，你必须拥有一台显存>10G的Nvidia 显卡才行呢。

**Comment by freelf** [comment]
> 抱歉应该是不可以，你必须拥有一台显存>10G的Nvidia 显卡才行呢。

AMD显卡不行是么

**Comment by mazzzystar** [comment]
@zhangdongpo 
因为需要支持CUDA。

**Comment by jwc19890114** [comment]
> 

可以通过调小参数来降低显存需求吗，我现在只有一张2070s

**Comment by mazzzystar** [comment]
@jwc19890114 
目前`CLIP`用到了3个模型，`ViTB32 + ViTB16 + RN50 `，每一个都提取embedding然后融合求平均。你可以改成只用`ViTB32`，或`ViTB32+RN50`，不想用的模型就设置成`False`，显存应该会降低。

https://github.com/mazzzystar/disco-diffusion-wrapper/blob/148262c34ea45f094a9d4ef1536a80f1c1201602/wrapper/mutils.py#L1264-L1271

**Comment by ampereking** [comment]
使用的A1000，4G
按照您说的，只用了ViTB32
一开始显存使用确实比使用三个模型的时候少很多
然后显存占用到一个平台期，突然急剧上升，然后OOM了
请教一下该怎么办

> @jwc19890114 目前`CLIP`用到了3个模型，`ViTB32 + ViTB16 + RN50 `，每一个都提取embedding然后融合求平均。你可以改成只用`ViTB32`，或`ViTB32+RN50`，不想用的模型就设置成`False`，显存应该会降低。
> 
> https://github.com/mazzzystar/disco-diffusion-wrapper/blob/148262c34ea45f094a9d4ef1536a80f1c1201602/wrapper/mutils.py#L1264-L1271

**Comment by mazzzystar** [comment]
@ampereking 这个显存的确可能跑不起来，可以先试试将图像的尺寸调小一些，例如`512x512`。如果还不行，试试只用RN50。

**Comment by ampereking** [comment]
> 
请问下图像尺寸是在mutils.py中190行吗？
如果是，那4G就没办法跑起来了
我设置到512*512，只用RN50，也提示显存OOM


> @ampereking 这个显存的确可能跑不起来，可以先试试将图像的尺寸调小一些，例如`512x512`。如果还不行，试试只用RN50。

**Comment by mazzzystar** [comment]
@ampereking 
生效的配置是改这里，可以试试改成256x256呢？
https://github.com/mazzzystar/disco-diffusion-wrapper/blob/5ea541417cab456c8e12fbad4f47e5536855de8f/wrapper/mutils.py#L1832

**Comment by ampereking** [comment]
> @ampereking 生效的配置是改这里，可以试试改成256x256呢？
> 
> https://github.com/mazzzystar/disco-diffusion-wrapper/blob/5ea541417cab456c8e12fbad4f47e5536855de8f/wrapper/mutils.py#L1832

好的，我再试试，谢谢您

**Comment by ampereking** [comment]
> @ampereking 生效的配置是改这里，可以试试改成256x256呢？
> 
> https://github.com/mazzzystar/disco-diffusion-wrapper/blob/5ea541417cab456c8e12fbad4f47e5536855de8f/wrapper/mutils.py#L1832

4G显存看起来确实是不行的，改成512*512，只用RN50
显存还是爆掉了
thanks

**Comment by ampereking** [comment]
建议在readme里面标注一下，需要6g显存

**Comment by arkilis** [comment]
1060 6G显存可以吗？谢谢

**Comment by mazzzystar** [comment]
@arkilis 抱歉我自己没有在各类显卡测试过，我找到了另一个repo，对方集成了win版exe：[他给的配置要求是这个](https://github.com/zhaoyun0071/Disco-Diffusion-Local#4%E6%98%BE%E5%8D%A1%E9%85%8D%E7%BD%AE%E9%9C%80%E6%B1%82)

我引用过来：
```
可能需要至少6GB显存，以下为测试情况：

（1） RTX2060 6G独显，图片尺寸256x512可行；

（2） RTX1070 8G独显，250steps耗时预估2小时，图片尺寸1280x720；

（3） RTX2070S 8G独显，450steps耗时预估16分钟，图片尺寸960x448；

（4） RTX3090 24G独显，450steps耗时预估10分钟，图片尺寸1280x720。

注：默认参数因为选了3个CLIP模型，如果想要尺寸更大，少选几个模型即可，但效果肯定有所影响，诸如6G独显的2060显卡，之选如下第一个模型，尺寸768×512都没问题：
```

**Comment by arkilis** [comment]
> @arkilis 抱歉我自己没有在各类显卡测试过，我找到了另一个repo，对方集成了win版exe：[他给的配置要求是这个](https://github.com/zhaoyun0071/Disco-Diffusion-Local#4%E6%98%BE%E5%8D%A1%E9%85%8D%E7%BD%AE%E9%9C%80%E6%B1%82)
> 
> 我引用过来：
> 
> ```
> 可能需要至少6GB显存，以下为测试情况：
> 
> （1） RTX2060 6G独显，图片尺寸256x512可行；
> 
> （2） RTX1070 8G独显，250steps耗时预估2小时，图片尺寸1280x720；
> 
> （3） RTX2070S 8G独显，450steps耗时预估16分钟，图片尺寸960x448；
> 
> （4） RTX3090 24G独显，450steps耗时预估10分钟，图片尺寸1280x720。
> 
> 注：默认参数因为选了3个CLIP模型，如果想要尺寸更大，少选几个模型即可，但效果肯定有所影响，诸如6G独显的2060显卡，之选如下第一个模型，尺寸768×512都没问题：
> ```

感谢大神，1280x720必须3090？

**Comment by mazzzystar** [comment]
@arkilis 
不一定，一个参考例子是我在`Nvidia Tesla T4`显卡(16G)也能跑1280x720，能跑多大尺寸取决于显存，速度快慢取决于算力。
