### ISSUE TITLE
Mac M1系统报错："slow_conv2d_cpu" not implemented for 'Half' 

### ISSUE THREAD

**Issue by Max-Liu** [mazzzystar/disco-diffusion-wrapper#20]
查了一下原因
In order to save GPU memory consumption and speed up inference, Real-ESRGAN uses half precision (fp16) during inference by default. However, some operators for half inference are not implemented in CPU mode. You need to add --fp32 option for the commands. For example, python inference_realesrgan.py -n RealESRGAN_x4plus.pth -i inputs --fp32.

把run.py中的改成model.convert_to_fp32()，还是不行

**Comment by mazzzystar** [comment]
这个repo里没用到Real-ESRGAN，你可以去Real-ESRGAN这个Repo下问一下。
你也可以安装它的推荐试一下？
```
python inference_realesrgan.py -n RealESRGAN_x4plus.pth -i inputs --fp32
```
