### ISSUE TITLE
Windows系统之下能安装dbus-python吗

### ISSUE THREAD

**Issue by ayachi3** [mazzzystar/disco-diffusion-wrapper#21]
请问在Windows下是否可以安装以下的安装包？
![image](https://user-images.githubusercontent.com/75938599/187654063-a0771e0d-5ed2-4fce-a3c6-661e693bfc75.png)

**Comment by mazzzystar** [comment]
可以不安装的，应该不影响模型。我在`requirements.txt`里删去了。
因为是直接`pip freeze`服务器的环境，所以存在很多包是冗余、模型不需要的，之前已经删去了一些，抱歉~

**Comment by ayachi3** [comment]
谢谢，问题解决了，不过6G的显卡好像运行不了，即使是只留下一个True并且将图片尺寸变成64*64也会超出显存限制，应该是因为6G显存并没有完全分配给这个程序使用，您知道如何解决吗？
![image](https://user-images.githubusercontent.com/75938599/187894148-4ef67bc5-ee89-457c-b66e-e2af39f68313.png)

**Comment by mazzzystar** [comment]
我没有在6G的显存上运行过，但应该是可以的，你可以试试换CLIP模型，似乎不同的CLIP显存占用不同，试试`ViTB-32`，图像尺寸设置为`512x512`。

在这里改尺寸：
https://github.com/mazzzystar/disco-diffusion-wrapper/blob/49d75c4d601dfece1c39120be7b95b13b9f2d89c/wrapper/mutils.py#L1832

**Comment by ayachi3** [comment]
谢谢大佬，运行起来了。不过它会在200代时停止，而不是240代，请问这是为什么呢？
![image](https://user-images.githubusercontent.com/75938599/188267570-5afb8f4a-8949-4fd3-accc-673ba91632d7.png)

**Comment by mazzzystar** [comment]
https://github.com/mazzzystar/disco-diffusion-wrapper/blob/49d75c4d601dfece1c39120be7b95b13b9f2d89c/wrapper/run.py#L45

这里steps改成241试试，之所以是241而不是240，涉及到图像保存：
https://github.com/mazzzystar/disco-diffusion-wrapper/blob/49d75c4d601dfece1c39120be7b95b13b9f2d89c/wrapper/mutils.py#L954-L960

你可以自己试试看。
抱歉我没有维护好这些~
