### ISSUE TITLE
wrapper/mutils.py 文件中有很多未定义变量。

### ISSUE THREAD

**Issue by kangwb** [mazzzystar/disco-diffusion-wrapper#29]
虽然程序可以运行，但是看到mutils中有非常多的未定义变量，是怎么回事呢？

**Comment by mazzzystar** [comment]
抱歉，之前关注了`diffusers` repo的issue，导致信息被吞没了。
我把一些主要变量提取出来做成可配置的了，非主要变量我就没动，是写死的。
