### ISSUE TITLE
run wrapper/utils.py报错#3

### ISSUE THREAD

**Issue by michael7908** [mazzzystar/disco-diffusion-wrapper#3]
您好，在公号看到您的大作，run on Colab
wrapper/utils.py

disco_xform_utils.py failed to import InferenceHelper. Please ensure that AdaBins directory is in the path (i.e. via sys.path.append('./AdaBins') or other means).
Using device: cuda:0
disco_xform_utils.py failed to import InferenceHelper. Please ensure that AdaBins directory is in the path (i.e. via sys.path.append('./AdaBins') or other means).

请问如何解决？十分感谢！

**Comment by mazzzystar** [comment]
Hi 首先抱歉，因为用wget下载模型速度太慢，我选择从代码里url手动提前下载好，所以没有来得及重新测试。
我刚重新测试了代码，并顺利通过了。你可以pull最新代码，直接进`wrapper`目录下，执行
```
python mutils.py
```
应该能正常下载全部的模型。

**Comment by jandy0414** [comment]
这个 models 下 那个文件手动去下载可以，但是  infer 这个 pretrained下的文件执行代码，或手动去下载
也下载不来。
![image](https://user-images.githubusercontent.com/35617197/167242856-a957857e-1cd7-40e5-9a26-64d9855e5130.png)

**Comment by mazzzystar** [comment]
@jandy0414 
我把这个文件单独上传到realease了。
这个应该能在服务器下载:
https://github.com/mazzzystar/disco-diffusion-wrapper/releases/download/v0.1.0/AdaBins_nyu.pt
