### ISSUE TITLE
运行不起来--报错 UnicodeDecodeError: 'gbk' codec can't decode byte 0x98 in position 2410: illegal multibyte sequence

### ISSUE THREAD

**Issue by jandy0414** [mazzzystar/disco-diffusion-wrapper#4]
![image](https://user-images.githubusercontent.com/35617197/167530585-f568c51d-82b9-473d-99e2-45b70ceef283.png)

![image](https://user-images.githubusercontent.com/35617197/167530631-3e26a65f-1cd1-4f08-8a17-bb419778f246.png)

**Comment by mazzzystar** [comment]
看上去编码的问题，可以说一下python版本号，以及，使用了中文吗？
可以参考：https://stackoverflow.com/questions/28165639/unicodedecodeerror-gbk-codec-cant-decode-byte-0x80-in-position-0-illegal-mult

**Comment by jandy0414** [comment]
> 看上去编码的问题，可以说一下python版本号，以及，使用了中文吗？ 可以参考：https://stackoverflow.com/questions/28165639/unicodedecodeerror-gbk-codec-cant-decode-byte-0x80-in-position-0-illegal-mult

python 版本我装了最新3.10.4的

**Comment by mazzzystar** [comment]
我在linux上运行应该是没有问题的，gbk肯定是和汉字相关的问题，你可以试试在`mutils.py`代码开头加上：
```python
# coding=utf-8
```
如果仍不行，可以试试把`mutils.py`里包含的中文先删除看看。

**Comment by jandy0414** [comment]
> https://stackoverflow.com/questions/28165639/unicodedecodeerror-gbk-codec-cant-decode-byte-0x80-in-position-0-illegal-mult

我弄了两个环境，之前python3.6 报了一个版本太低问题，但是那个环境下，读取文件有个：encoding="utf-8"
所以我对应的python3.10环境，代码给它加上去，没报错了。
![image](https://user-images.githubusercontent.com/35617197/167547290-4c79f78c-09a3-4531-ac74-3ea5d759108f.png)


但是新的问题来了，报：找不到：midas.dpt_depth   环境目录下是存在了
我把目录MiDas目录，删除，重新跑，也还是报错
![image](https://user-images.githubusercontent.com/35617197/167547885-636ad3b5-225e-4030-a978-65b6ebfe7711.png)

**Comment by mazzzystar** [comment]
本质是在加载这个模型：https://github.com/isl-org/MiDaS/tree/master/midas，里面有`dpt_depth.py`文件。
你出错有可能是：
1.`MiDas`并没有被加入`sys`环境，导致没办法直接调用`MiDas.midas.dpt_depth`文件
https://github.com/mazzzystar/disco-diffusion-wrapper/blob/148262c34ea45f094a9d4ef1536a80f1c1201602/wrapper/mutils.py#L93
可以检索"python 打印sys环境"看看。

2.`MiDas/midas/`目录下找不到[dpt_depth.py](https://github.com/isl-org/MiDaS/blob/master/midas/dpt_depth.py)

**Comment by jandy0414** [comment]
> "python 打印sys环境

----在pycharm 运行能过了，新问题：---
代码中的auth_key 请问，是直接用在deepl官网下这个后缀为：:fx的 key吗？？？
![image](https://user-images.githubusercontent.com/35617197/167764904-eb7eaec4-bf2f-4746-8a80-4754b598f34d.png)

执行代码的时候报错：
![image](https://user-images.githubusercontent.com/35617197/167764954-8d1b5db7-7775-461e-90d3-fc89dc269859.png)

**Comment by mazzzystar** [comment]
是这个，授权失败应该是你的deepl没有注册成功(所以这个密钥无效)，似乎必须美国信用卡号，或者特殊途径搞到~
