### ISSUE TITLE
Mac 平台   我把deepl key 换上了 但是命令行运行抛出了这个错

### ISSUE THREAD

**Issue by trumanicu** [mazzzystar/disco-diffusion-wrapper#7]
ff@FFdeMacBook-Pro wrapper % python run.py "一行白鹭上青天"
  File "run.py", line 16
    0: [f"{text}"],
                ^
SyntaxError: invalid syntax
ff@FFdeMacBook-Pro wrapper % touch sentence.list
ff@FFdeMacBook-Pro wrapper % python batch_run.py
/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'batch_run.py': [Errno 2] No such file or directory
ff@FFdeMacBook-Pro wrapper %

**Comment by trumanicu** [comment]
我是iOS开发，对python 不熟  装的是3.9.5的Python

**Comment by trumanicu** [comment]
从公众号慕名而来！

**Comment by mazzzystar** [comment]
`pip install -r requirements.txt` 这一步有执行吗？这个报错是语法错误，但Python3上不应该出现这个报错才对。
另外这个模型需要在GPU下运行呢。

**Comment by trumanicu** [comment]
pip install -r requirements.txt 执行完了 
ERROR: Could not find a version that satisfies the requirement cloud-init==20.1 (from versions: none)
ERROR: No matching distribution found for cloud-init==20.1
ff@FFdeMacBook-Pro disco-diffusion-wrapper % pip install --upgrade pip
zsh: command not found: pip
ff@FFdeMacBook-Pro disco-diffusion-wrapper % pip3 install --upgrade pip3
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement pip3 (from versions: none)
ERROR: No matching distribution found for pip3
ff@FFdeMacBook-Pro disco-diffusion-wrapper % pip3 install --upgrade pip 
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pip in /Users/ff/Library/Python/3.8/lib/python/site-packages (22.0.4)
Collecting pip
  Downloading pip-22.1-py3-none-any.whl (2.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 386.2 kB/s eta 0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 22.0.4
    Uninstalling pip-22.0.4:
      Successfully uninstalled pip-22.0.4
  WARNING: The scripts pip, pip3, pip3.10 and pip3.8 are installed in '/Users/ff/Library/Python/3.8/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed pip-22.1
ff@FFdeMacBook-Pro disco-diffusion-wrapper % --no-warn-script-location
zsh: command not found: --no-warn-script-location
ff@FFdeMacBook-Pro disco-diffusion-wrapper % pip3 install --upgrade pip --no-warn-script-location
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pip in /Users/ff/Library/Python/3.8/lib/python/site-packages (22.1)

**Comment by mazzzystar** [comment]
`cloud-init==20.1`是是云环境虚拟机的一个包，你应该用不到。你再`git pull`一下最新代码呢？我把它从requirments.txt里去掉了。
