### ISSUE TITLE
run.py和run_batch.py设置steps无法生效

### ISSUE THREAD

**Issue by IvesZhang** [mazzzystar/disco-diffusion-wrapper#9]
在run.py文件中调整了执行步数，但是无法生效..

`diffuse(text_prompts, outdirName, steps=21, image_prompts=image_prompts, init_image=input_img_path, display_rate=2)`

steps应该是21，但是实际运行过程中依然需要跑240.

run_batch.py同样是这个现象，请问应该如何解决呢？

**Comment by mazzzystar** [comment]
感谢反馈，新commit已修复此问题。

**Comment by IvesZhang** [comment]
> 感谢反馈，新commit已修复此问题。

pull了新代码，还是无法手动设置steps呢....依然需要跑240步才生成图像

我目前需要在mutil.py中更改steps才能生效（run.py和run_batch.py中均无法生效）

**Comment by mazzzystar** [comment]
我测试过并不会呀，在这里修改steps是可以生效的：
https://github.com/mazzzystar/disco-diffusion-wrapper/blob/f79fc615ef51816899bdaa46dfc5d078146422a4/wrapper/run_batch.py#L135

**Comment by Leocien** [comment]
> IvesZhang

我pull的最新的代码，修改这里的steps仍然不work。。。

**Comment by THU-lsy** [comment]
> 我测试过并不会呀，在这里修改steps是可以生效的：
> 
> https://github.com/mazzzystar/disco-diffusion-wrapper/blob/f79fc615ef51816899bdaa46dfc5d078146422a4/wrapper/run_batch.py#L135
我pull的最新的代码，修改这里的steps仍然不work。。。
